### ISSUE TITLE
aeyoll/laravel-free-mobile-notification

### ISSUE THREAD

**Issue by KhaingWah** [aeyoll/laravel-free-mobile-notification-sender#1]
When I publish the following command:
  php artisan config:publish aeyoll/laravel-free-mobile-notification-sender

And also for getting the problem with userid and apikey from your user profile on mobile.free.fr.

{"error":{"type":"Symfony\Component\Debug\Exception\FatalErrorException","message":"Class 'Aeyoll\LaravelFreeMobile
NotificationSender\LaravelFreeMobileNotificationSenderServiceProvider' not found",
xampp\htdocs\test\vendor\laravel\framework\src\Illuminate\Foundation\ProviderRepos
itory.php","line":158

Thanks,
Kai.

**Comment by aeyoll** [comment]
Looks like your dependencies are not up-to-date, did you correctly added "aeyoll/laravel-free-mobile-notification-sender": "1.*" in the require part of your composer.json?

**Comment by aeyoll** [comment]
I'm closing the issue, feel free to reopen it if it's needed.
